Fiver.Security.Bearer/Models/Token/LoginInputModel.cs
namespace Fiver.Security.Bearer.Models.Token
{
    public class LoginInputModel
    {
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

Fiver.Security.Bearer/Controllers/JQueryController.cs
using Microsoft.AspNetCore.Mvc;

namespace Fiver.Security.Bearer.Controllers
{
    public class JQueryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Fiver.Security.Bearer/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Fiver.Security.Bearer.Controllers
{
    [Authorize(Policy = "Member")]
    [Route("movies")]
    public class MoviesController : Controller
    {
        [HttpGet]
        public IActionResult Get()
        {
            //return Content("List of Movies");

            var dict = new Dictionary<string, string>();
            HttpContext.User.Claims.ToList().ForEach(item => dict.Add(item.Type, item.Value));

            return Ok(dict);
        }
    }
}

Fiver.Security.Bearer/Controllers/TokenController.cs
using Microsoft.AspNetCore.Mvc;
using Fiver.Security.Bearer.Models.Token;
using Fiver.Security.Bearer.Helpers;
using Microsoft.AspNetCore.Authorization;

namespace Fiver.Security.Bearer.Controllers
{
    [Route("token")]
    [AllowAnonymous]
    public class TokenController : Controller
    {
        [HttpPost]
        public IActionResult Create([FromBody]LoginInputModel inputModel)
        {
            if (inputModel.Username != "james" && inputModel.Password != "bond")
                return Unauthorized();

            var token = new JwtTokenBuilder()
                                .AddSecurityKey(JwtSecurityKey.Create("fiver-secret-key"))
                                .AddSubject("james bond")
                                .AddIssuer("Fiver.Security.Bearer")
                                .AddAudience("Fiver.Security.Bearer")
                                .AddClaim("MembershipId", "111")
                                .AddExpiry(1)
                                .Build();

            //return Ok(token);
            return Ok(token.Value);
        }
    }
}

Fiver.Security.Bearer/Views/JQuery/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ASP.NET Core Bearer Auth</title>

    <script src="~/js/jquery.min.js"></script>

</head>
<body>
    <div>
        <h1>ASP.NET Core Bearer Auth</h1>

        <input type="button" id="GetToken" value="Get Token" />
        <div id="token"></div>
        <hr />
        <input type="button" id="UseToken" value="Use Token" />
        <div id="result"></div>
    </div>
    <script>
        $(function () {
            $("#GetToken").click(function () {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Create", "Token")',
                    data: JSON.stringify({ "Username": "james", "Password": "bond" }),
                    contentType: "application/json"
                }).done(function (data, statusText, xhdr) {
                    $("#token").text(data);
                }).fail(function (xhdr, statusText, errorText) {
                    $("#token").text(errorText);
                });
            });

            $("#UseToken").click(function () {
                $.ajax({
                    method: 'GET',
                    url: '@Url.Action("Get", "Movies")',
                    beforeSend: function (xhdr) {
                        xhdr.setRequestHeader("Authorization", "Bearer " + $("#token").text());
                    }
                }).done(function (data, statusText, xhdr) {
                    $("#result").text(JSON.stringify(data));
                }).fail(function (xhdr, statusText, errorText) {
                    $("#result").text(JSON.stringify(xhdr));
                });
            });
        });
    </script>
</body>
</html>